name: Download Full Binance Data

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Download full SQLite database
        run: |
          wget --timeout=120 --tries=5 \
          "https://www.abzarsaz.com/xmoon/candles/binance_data/btcusdt_1m_full_from_2025-01-01.sqlite3" \
          -O btcusdt_1m_full_from_2025-01-01.sqlite3

          ls -lh btcusdt_1m_full_from_2025-01-01.sqlite3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: btcusdt-1m-full-from-2025
          path: btcusdt_1m_full_from_2025-01-01.sqlite3
          compression-level: 6
          retention-days: 7
